### ISSUE TITLE
Only show 6 case box to Customers and not to Retailers and Wholesalers

### ISSUE THREAD

**Issue by taeche** [taeche/SoDoEx#1]
Currently both 6 can box and 48 can master case are displayed for all user types.  The requirement is to only show 6 can box to customers only.

**Comment by daypekr** [comment]
형,

카톡으로 형이 말한것 내가 잘 못 이해한것 같은데...

[image: Inline image 1]

나는, 6 can product를 retail, wholesaler일경우 보이지 않도록 한다라고 생각했거든.

그래서, retailer, wholesaler로 로그인하면 dropdown에서 6 can product가 안나오도록 해둔거야.

[image: Inline image 2]

[image: Inline image 3]

질문!
1. 형이 했을때는 여전히 6 can, 48 can이 role에 상관없이 모두 보여지는거야?
2. 위에 implementation 한것처럼이 아니라, customer에게는 6 can box만 보이고 48 can box는
   감춰야 하는거야?

ㄱ

**Comment by taeche** [comment]
that's right.  only show it to the customers.

Date: Thu, 11 Feb 2016 12:17:16 -0800

**Comment by daypekr** [comment]
ok. let me take care of it tomorrow

ㄹㄹ

**Comment by taeche** [comment]
Verified and closing the issue.
