### ISSUE TITLE
Link the facebook page on the home page.

### ISSUE THREAD

**Issue by taeche** [taeche/SoDoEx#14]
The following page has been created on Facebook to promote SoDoEx.  https://www.facebook.com/sodoex/.  Let's link it on the home page.  Should we use Facebook icon?

**Comment by daypekr** [comment]
Facebook link is added to DEV site.
The icon is originally included in the theme(jv-allinone).
Can we go live with this one?

![image](https://cloud.githubusercontent.com/assets/8378894/13753970/93339be6-ea58-11e5-8d89-0037c44b2923.png)

**Comment by taeche** [comment]
That's fine.

Date: Mon, 14 Mar 2016 10:50:33 -0700

**Comment by daypekr** [comment]
## Developer comment for further maintenance.

No source code modification made.
It is completely done in the admin page.

Instruction:
go Admin > Appearance > widget
find Panel Header box
Add text widget on to it
put the script blow to the content text area
put the pull-right class name to the class name textbox

Reference screen capture.
![image](https://cloud.githubusercontent.com/assets/8378894/13806228/b11f8d22-eb9d-11e5-820d-f46e53bd0a1e.png)

**Comment by daypekr** [comment]
Deployed to prouduction
