### ISSUE TITLE
Clicking Buy Now button only shows 500ml options

### ISSUE THREAD

**Issue by taeche** [taeche/SoDoEx#16]
Repro Steps:
1) From home page, click on 'buy now' button

Actual Result:
The page navigates to https://sodoex.com/product/sodoex/ and only shows the 500ml option

Expected Result:
The page needs to navigate to https://sodoex.com/shop/ and show both 500ml and 300ml options.

**Comment by daypekr** [comment]
Fixed. Please check it out in DEV site.

**Comment by taeche** [comment]
Verified

**Comment by daypekr** [comment]
Fixed in Production. Please check it out.
