### ISSUE TITLE
The page nage for 500ml should be consistent with 300ml

### ISSUE THREAD

**Issue by taeche** [taeche/SoDoEx#17]
Repro Steps:
1) Navigate to 500ml product page - https://sodoex.com/product/sodoex/

Actual Result:
The page naviages to https://sodoex.com/product/sodoex/

Expected Result:
The page should be renamed to https://sodoex.com/product/sodoex-500ml/ so that it's consistent with 300ml page.

**Comment by daypekr** [comment]
Fixed. Please check it out in DEV site.

**Comment by taeche** [comment]
Verified

**Comment by daypekr** [comment]
Fixed in Production. Please check it out.
