### ISSUE TITLE
Automatically generate invoices

### ISSUE THREAD

**Issue by taeche** [taeche/SoDoEx#2]
[NECO Global Inc Invoice Template.docx](https://github.com/taeche/SoDoEx/files/131177/NECO.Global.Inc.Invoice.Template.docx)

Can we populate and generate the linked invoice whenever orders are completed from our web site?

**Comment by daypekr** [comment]
I found a plugin for pdf invoice.
Please find sample invoice generated by the plugin installed in my local machine.
The template is not the same layout as the docx file you've attached.
Let me know if we can use this pdf layout, or we should follow the layout of the docx file.
[invoice-invoice233.pdf](https://github.com/taeche/SoDoEx/files/133719/invoice-invoice233.pdf)

**Comment by taeche** [comment]
Looks good.  Could put our company logo?  I've asked Sung Jin to create one.

**Comment by daypekr** [comment]
Sure. Just send me the logo when it's created.

**Comment by daypekr** [comment]
The feature is added to Dev site without company logo.
Send me the company logo when it is created.

For testing purpose, invoices are available not only for completed orders, but also orders in other statuses. eg, cancelled order.
Please check it out at My Account page.

![image](https://cloud.githubusercontent.com/assets/8378894/13373313/8692b024-dda7-11e5-91d2-59b369246b57.png)

**Comment by taeche** [comment]
ok, i'll check.

Date: Sat, 27 Feb 2016 06:14:43 -0800

**Comment by taeche** [comment]
Some changes:
1) replace NECO Global Inc. with SODO Distribution
2) Remove weight information

**Comment by daypekr** [comment]
The requested changes above has been applied to DEV.
Please check it out.

**Comment by taeche** [comment]
go ahead and push to production.

Date: Sun, 28 Feb 2016 11:01:13 -0800

**Comment by daypekr** [comment]
It's deployed to production.
Please be noticed that users can ONLY see  the invoices of completed orders, not of them in other status.
