### ISSUE TITLE
When master cases count is equal to or greater than 10 then provide an informational message to the users

### ISSUE THREAD

**Issue by taeche** [taeche/SoDoEx#3]
Since shipping a pallet is more cost effective, we want to make sure the customers are aware of this.  When master case count is equal to or greater than 10 then we need to provide an information message to the users.  "Please contact the SoDoEx team, when you are purchasing 10 master cases or more to lower your shipping cost."

**Comment by daypekr** [comment]
Task is done and deployed to dev site.
Please confirm it so I can deploy it to production.
Note that the notification will show up when the total weight of items in the cart equal to or greater than 10 items.
Quantity based logic might be fragile because checking quantity need product id which are different between dev and production.

**Comment by taeche** [comment]
Looks good..  Let's tweak the wording little bit.
"Please contact the SoDoEx team (sodoex@outlook.com) when you are purchasing 10 master cases or more to lower your shipping cost."

**Comment by daypekr** [comment]
The message has been updated. Please check it out on Dev site.

**Comment by taeche** [comment]
Looks good.  Please close the item once deployed to Production

Date: Sun, 21 Feb 2016 00:02:01 -0800

**Comment by daypekr** [comment]
It's been deployed to Production.
Please check it out.

**Comment by taeche** [comment]
Re-opening the issue.  We are now going with free shipping once the order amount is greater than $100.00.  Please remove the message.  :)

**Comment by daypekr** [comment]
In DEV site, free shipping option is added for orders $100 or more, and the message about shipping cost for bulk order is hidden.

Please check this out and let me know whether to go live or not.

![image](https://cloud.githubusercontent.com/assets/8378894/13747208/878cde74-ea3a-11e5-9bd0-8f81490e0c38.png)

**Comment by taeche** [comment]
Checked... Please post to production and close the issue

**Comment by daypekr** [comment]
## Developer comment for further maintenance

This is done in the admin page.
Popup messages can be turned on or turned off in
Admin >  Ninja announcements

![image](https://cloud.githubusercontent.com/assets/8378894/13806481/441970ec-eb9f-11e5-9129-0293e90021e9.png)

**Comment by daypekr** [comment]
Deployed to production.
