### ISSUE TITLE
Differentiate Retailers and Wholesaler from the Store Map

### ISSUE THREAD

**Issue by taeche** [taeche/SoDoEx#5]
1) Extend the Store Locator plugin settings.  Create an option to select Retailers and Wholesalers marker.
2) Display the selected markers on the Store Map for retailers and wholesalers.

**Comment by daypekr** [comment]
The task is done and deployed to DEV site.
Please check it out.

Task details
1. added additional field in the admin page to select marker icon for each category.
   ![marker1](https://cloud.githubusercontent.com/assets/8378894/13372563/789e7d70-dd8b-11e5-94b3-2ff7546caa12.png)

2.added Category dropdown to the selection criteria of store page.
  The map is now displaying shop marker in different color by category.
![image](https://cloud.githubusercontent.com/assets/8378894/13372570/cb0b3814-dd8b-11e5-9fb5-77656ceb399f.png)
