### ISSUE TITLE
Filter the stores automatically when the Category dropdown is selected instead of relying on the Search button

### ISSUE THREAD

**Issue by taeche** [taeche/SoDoEx#7]
Filter the stores automatically when the Category dropdown is selected instead of relying on the Search button

**Comment by daypekr** [comment]
The job is done and deployed to DEV.

NOTE: Not only the category dropdown triggers search function, but also changing value of any dropdown in the selection criteria will trigger it. Because it seems more reasonable.

**Comment by taeche** [comment]
verified... please promote to production

**Comment by daypekr** [comment]
Deployed to production.

**Comment by taeche** [comment]
I don't see the changes reflected in Production.

**Comment by daypekr** [comment]
A javascript file has been updated.
Can you delete your local cache in the browser and try it again?
Please let me know if it still doesn't work after that.

**Comment by taeche** [comment]
I deleted all files and still cannot see the new dropdown list.  Also not able to see the ability to select the different Marker for the store category from the admin screen.

Date: Wed, 16 Mar 2016 13:31:28 -0700

**Comment by taeche** [comment]
This is in production.

From: tae.chekal@outlook.com
To: reply@reply.github.com
Subject: RE: [SoDoEx] Filter the stores automatically when the Category dropdown is selected instead of relying on the Search button (#7)
Date: Thu, 17 Mar 2016 00:50:35 -0700

I deleted all files and still cannot see the new dropdown list.  Also not able to see the ability to select the different Marker for the store category from the admin screen.

Date: Wed, 16 Mar 2016 13:31:28 -0700

**Comment by daypekr** [comment]
Sorry for not deploying #5, about adding category dropdown, which is the parent issue on this.
It is fully deployed to production now.
Could you please check it out in Production again?

**Comment by daypekr** [comment]
## Developer note

To display category dropdown, 
_Show the category doropdown?_ setting in Store Locator setting page must be turned on as below screen shot.
![image](https://cloud.githubusercontent.com/assets/8378894/13840924/1627d28a-ec69-11e5-8e0d-c5c1a17bb2da.png)

Change marker function is implemented in function.php of the theme.
![image](https://cloud.githubusercontent.com/assets/8378894/13840954/4e69b4ec-ec69-11e5-9357-379a179efdb3.png)

**Comment by taeche** [comment]
verified in production

**Comment by daypekr** [comment]
Let me close the issue
